#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

const envPath = path.join(__dirname, '..', '.env.local');

console.log('🚀 YouTube Learning Platform - Environment Setup\n');

// Check if .env.local already exists
if (fs.existsSync(envPath)) {
  console.log('⚠️  .env.local file already exists!');
  rl.question('Do you want to overwrite it? (y/N): ', (answer) => {
    if (answer.toLowerCase() === 'y' || answer.toLowerCase() === 'yes') {
      setupEnvironment();
    } else {
      console.log('Setup cancelled.');
      rl.close();
    }
  });
} else {
  setupEnvironment();
}

function setupEnvironment() {
  console.log('\n📝 Setting up environment variables...\n');
  
  const envContent = [];
  
  rl.question('Enter your Gemini API Key (required for AI features): ', (geminiKey) => {
    if (geminiKey.trim()) {
      envContent.push(`GEMINI_API_KEY=${geminiKey.trim()}`);
    } else {
      console.log('⚠️  No Gemini API key provided. AI features will not work.');
      envContent.push('# GEMINI_API_KEY=your_gemini_api_key_here');
    }
    
    rl.question('\nEnter your YouTube API Key (optional): ', (youtubeKey) => {
      if (youtubeKey.trim()) {
        envContent.push(`NEXT_PUBLIC_YOUTUBE_API_KEY=${youtubeKey.trim()}`);
      } else {
        envContent.push('# NEXT_PUBLIC_YOUTUBE_API_KEY=your_youtube_api_key_here');
      }
      
      rl.question('\nEnter your Groq API Key (optional): ', (groqKey) => {
        if (groqKey.trim()) {
          envContent.push(`GROQ_API_KEY=${groqKey.trim()}`);
        } else {
          envContent.push('# GROQ_API_KEY=your_groq_api_key_here');
        }
        
        // Write the .env.local file
        const finalContent = [
          '# YouTube Learning Platform Environment Variables',
          '# Generated by setup script',
          '',
          ...envContent,
          '',
          '# Get your Gemini API key from: https://makersuite.google.com/app/apikey',
          '# Get your YouTube API key from: https://console.developers.google.com/',
          '# Get your Groq API key from: https://console.groq.com/'
        ].join('\n');
        
        fs.writeFileSync(envPath, finalContent);
        
        console.log('\n✅ Environment variables saved to .env.local');
        console.log('\n🔄 Please restart your development server for changes to take effect.');
        console.log('\n📚 For more information, see SETUP.md');
        
        rl.close();
      });
    });
  });
}
